/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msi15' at '8/4/16 10:18 AM' with Gradle 2.12
 *
 * @author msi15, @date 8/4/16 10:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
